sudo: false
language: node_js

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_success:
  - "./bin/bower_build"

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    tags: true
    repo: emberjs/ember-mocha
