sudo: false

language: node_js
node_js:
  - 6

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --no-lockfile
  - bower install

script:
  - yarn test

deploy:
  - provider: npm
    email: stefan.penner+ember-cli@gmail.com
    api_key:
      secure: PQRsq4JcFYPXOqov1jwPw63WnwYYpyKby/2akUjq8PHwwgCDEt34Z8yqQdJogqKmKRjijsiWu+b54fbIpZ6TMvqPL18F8FbCl6e2zoAY55VUmmVkx9wkvuPydTDs2fuPqk6LFvmIMiq+pjEPlSeWg3GpFSkFjfs0WZlO33xMyWw=
    on:
      tags: true
      repo: emberjs/ember-mocha

  - provider: script
    script: .travis/deploy.sh
    on:
      tags: true
      repo: emberjs/ember-mocha
